site_name: 'Tensor: Scientific Computing for PHP'

theme:
  name: material
  logo: images/app-icon-medium.png
  favicon: images/app-icon-small.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

nav:
  - Home: https://rubixml.com
  - Getting Started:
    - Welcome: index.md
  - API Reference:
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RubixML/Tensor
    - icon: fontawesome/brands/telegram
      link: https://t.me/RubixML
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RubixML
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8952251/

use_directory_urls: false

plugins:
  - search
  - git-revision-date

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
  - footnotes

google_analytics:
  - UA-136137674-1
  - auto

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

extra_css:
  - css/custom.css

repo_url: https://github.com/RubixML/Tensor
site_url: https://rubixml.com
site_description: 'Tensor is a library and extension that provides objects for scientific computing in PHP.'

copyright: '&copy; 2021 Rubix ML'
